const board = [
  { id: 0, color: 'light' },
  { id: 1, color: 'dark', piece: { id: 1, team: 'Black', presentPosition: 1, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 2, color: 'light' },
  { id: 3, color: 'dark', piece: { id: 2, team: 'Black', presentPosition: 3, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 4, color: 'light' },
  { id: 5, color: 'dark', piece: { id: 3, team: 'Black', presentPosition: 5, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 6, color: 'light' },
  { id: 7, color: 'dark', piece: { id: 4, team: 'Black', presentPosition: 7, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},

  { id: 8, color: 'dark', piece: { id: 5, team: 'Black', presentPosition: 8, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 9, color: 'light' },
  { id: 10, color: 'dark', piece: { id: 6, team: 'Black', presentPosition: 10, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 11, color: 'light' },
  { id: 12, color: 'dark', piece: { id: 7, team: 'Black', presentPosition: 12, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 13, color: 'light' },
  { id: 14, color: 'dark', piece: { id: 8, team: 'Black', presentPosition: 14, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 15, color: 'light' },

  { id: 16, color: 'light' },
  { id: 17, color: 'dark', piece: { id: 9, team: 'Black', presentPosition: 17, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 18, color: 'light' },
  { id: 19, color: 'dark', piece: { id: 10, team: 'Black', presentPosition: 19, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 20, color: 'light' },
  { id: 21, color: 'dark', piece: { id: 11, team: 'Black', presentPosition: 21, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 22, color: 'light' },
  { id: 23, color: 'dark', piece: { id: 12, team: 'Black', presentPosition: 23, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},

  { id: 24, color: 'dark' },
  { id: 25, color: 'light' },
  { id: 26, color: 'dark' },
  { id: 27, color: 'light' },
  { id: 28, color: 'dark' },
  { id: 29, color: 'light' },
  { id: 30, color: 'dark' },
  { id: 31, color: 'light' },

  { id: 32, color: 'light' },
  { id: 33, color: 'dark' },
  { id: 34, color: 'light' },
  { id: 35, color: 'dark' },
  { id: 36, color: 'light' },
  { id: 37, color: 'dark' },
  { id: 38, color: 'light' },
  { id: 39, color: 'dark' },

  { id: 40, color: 'dark', piece: { id: 13, team: 'Red', presentPosition: 40, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 41, color: 'light' },
  { id: 42, color: 'dark', piece: { id: 14, team: 'Red', presentPosition: 42, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 43, color: 'light' },
  { id: 44, color: 'dark', piece: { id: 15, team: 'Red', presentPosition: 44, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 45, color: 'light' },
  { id: 46, color: 'dark', piece: { id: 16, team: 'Red', presentPosition: 46, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 47, color: 'light' },

  { id: 48, color: 'light' },
  { id: 49, color: 'dark', piece: { id: 17, team: 'Red', presentPosition: 49, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 50, color: 'light' },
  { id: 51, color: 'dark', piece: { id: 18, team: 'Red', presentPosition: 51, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 52, color: 'light' },
  { id: 53, color: 'dark', piece: { id: 19, team: 'Red', presentPosition: 53, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 54, color: 'light' },
  { id: 55, color: 'dark', piece: { id: 20, team: 'Red', presentPosition: 55, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},

  { id: 56, color: 'dark', piece: { id: 21, team: 'Red', presentPosition: 56, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 57, color: 'light' },
  { id: 58, color: 'dark', piece: { id: 22, team: 'Red', presentPosition: 58, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 59, color: 'light' },
  { id: 60, color: 'dark', piece: { id: 23, team: 'Red', presentPosition: 60, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 61, color: 'light' },
  { id: 62, color: 'dark', piece: { id: 24, team: 'Red', presentPosition: 62, isCaptured: false, isKing: false, availableMoves: [], canCapture: false, moveHistory: [], isMoving: false, hasDoubleJump: false, isHighlighted: false }},
  { id: 63, color: 'light' }
];

export default board;